# Generated by Django 4.1.2 on 2022-11-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikacija', '0002_gostiseznam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pospravljanje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Soba', models.IntegerField(max_length=2)),
                ('Akcija', models.CharField(max_length=20)),
                ('Za_Oseb', models.IntegerField(max_length=2)),
                ('Status', models.CharField(max_length=20)),
            ],
        ),
    ]
