# Generated by Django 4.1.2 on 2022-11-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikacija', '0003_pospravljanje'),
    ]

    operations = [
        migrations.CreateModel(
            name='PospravljanjePrihodi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Soba', models.IntegerField()),
                ('St_Oseb', models.IntegerField()),
                ('Zahteve', models.CharField(max_length=255)),
                ('Status', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='pospravljanje',
            name='Soba',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pospravljanje',
            name='Za_Oseb',
            field=models.IntegerField(),
        ),
    ]
