# Generated by Django 4.1.2 on 2022-11-14 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplikacija', '0004_pospravljanjeprihodi_alter_pospravljanje_soba_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pospravljanjeprihodi',
            name='Zahteve',
        ),
    ]
